version: '3.10.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  python_script:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
